---
abstract: 'lightweight Moo-based exception class factory'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.88
  Try::Tiny: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Throwable::Factory
name: Throwable-Factory
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Moo: 1.000006
  MooX::Struct: 0.009
  Throwable::Error: 0.200000
  namespace::clean: 0
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Throwable-Factory
  homepage: https://metacpan.org/release/Throwable-Factory
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-throwable-factory
version: 0.001
